# Generated by Django 5.0.4 on 2024-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('synopsis', models.TextField(null=True, verbose_name='Sinopsis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/covers/', verbose_name='Imagen')),
                ('duration', models.IntegerField(null=True, verbose_name='Duración')),
                ('genre', models.CharField(choices=[('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Ciencia Ficción', 'Ciencia Ficción'), ('No-Ficción', 'No-Ficción'), ('Drama', 'Drama'), ('Fantasía', 'Fantasía'), ('Musical', 'Musical'), ('Suspense', 'Suspense'), ('Terror', 'Terror'), ('Comedia', 'Comedia')], default='', max_length=30, verbose_name='Género')),
                ('subgenre', models.CharField(blank=True, choices=[('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Ciencia Ficción', 'Ciencia Ficción'), ('No-Ficción', 'No-Ficción'), ('Drama', 'Drama'), ('Fantasía', 'Fantasía'), ('Musical', 'Musical'), ('Suspense', 'Suspense'), ('Terror', 'Terror'), ('Comedia', 'Comedia')], default='', max_length=30, null=True, verbose_name='Subgénero')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Lanzamiento')),
                ('age_restriction', models.CharField(choices=[('0', 'G'), ('7', 'PG'), ('13', 'PG-13'), ('17', 'R'), ('18', 'NC-17')], max_length=2)),
                ('formats', models.ManyToManyField(related_name='films', to='Movie.format', verbose_name='Formato')),
            ],
        ),
    ]
