# Generated by Django 5.0.4 on 2024-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id_banner', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('description', models.CharField(max_length=30, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bannerImages/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
    ]
