# Generated by Django 5.0.4 on 2024-06-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Imagen'),
        ),
    ]
