# Generated by Django 5.0.4 on 2024-10-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='format',
        ),
        migrations.RemoveField(
            model_name='film',
            name='language',
        ),
        migrations.AddField(
            model_name='film',
            name='format',
            field=models.ManyToManyField(to='Movie.format'),
        ),
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.ManyToManyField(to='Movie.language'),
        ),
    ]
