# Generated by Django 5.0.4 on 2024-05-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='pelicula',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(null=True, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='anulate',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='shor_name',
        ),
    ]
