# Generated by Django 5.0.4 on 2024-06-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_alter_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age_restriction',
            field=models.CharField(choices=[('0', 'G (0+)'), ('7', 'PG (7+)'), ('13', 'PG-13 (13+)'), ('17', 'R (17+)'), ('18', 'NC-17 (18+)')], max_length=2),
        ),
    ]
