# Generated by Django 5.0.4 on 2024-05-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_alter_pelicula_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estreno',
        ),
    ]
