# Generated by Django 5.0.4 on 2024-06-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_alter_film_age_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='upcoming_releases',
            field=models.BooleanField(default=False, verbose_name='Próximos Lanzamientos'),
        ),
        migrations.AlterField(
            model_name='film',
            name='age_restriction',
            field=models.CharField(choices=[('ATP', 'ATP'), ('PM13', '13+'), ('PM16', '16+)'), ('PM18', '18+')], max_length=4),
        ),
    ]
