# Generated by Django 5.0.4 on 2024-05-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0004_alter_pelicula_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.FloatField(max_length=4, null=True, verbose_name='Duración'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(max_length=50, null=True, verbose_name='Género'),
        ),
    ]
