# Generated by Django 5.0.4 on 2024-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0004_film_upcoming_releases_alter_film_age_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age_restriction',
            field=models.CharField(choices=[('ATP', 'ATP'), ('PM13', '13+'), ('PM16', '16+'), ('PM18', '18+')], max_length=4, verbose_name='Restricción de edad'),
        ),
    ]
