# Generated by Django 5.0.4 on 2024-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0005_pelicula_duracion_pelicula_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(max_length=4, null=True, verbose_name='Duración'),
        ),
    ]
