# Generated by Django 5.0.4 on 2024-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0005_alter_film_age_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age_restriction',
            field=models.CharField(choices=[('ATP', 'ATP'), ('13', 'PM13'), ('16', 'PM16'), ('18', 'PM18')], max_length=4, verbose_name='Restricción de edad'),
        ),
    ]
