# Generated by Django 5.0.4 on 2024-05-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0006_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(null=True, verbose_name='Duración'),
        ),
    ]
