# Generated by Django 5.0.4 on 2024-12-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='contraseña_predeterminada', max_length=128),
        ),
    ]
