# Generated by Django 5.0.4 on 2024-12-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_remove_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
