# Generated by Django 5.0.4 on 2024-12-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='password_default', max_length=255),
            preserve_default=False,
        ),
    ]
