# Generated by Django 5.0.4 on 2024-12-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_alter_users_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
