# Generated by Django 5.0.4 on 2024-10-19 22:34

import Applications.Showtime.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id_price', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Promoción')),
                ('amount', models.PositiveIntegerField(verbose_name='Precio')),
                ('ticket_quantity', models.PositiveIntegerField(verbose_name='Cantidad de entradas')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
            },
        ),
        migrations.CreateModel(
            name='Movie_Theater',
            fields=[
                ('id_movie_theater', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('capacity', models.PositiveIntegerField(null=True, verbose_name='Capacidad')),
                ('formats', models.ManyToManyField(to='Movie.format')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_code', models.AutoField(primary_key=True, serialize=False)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.film')),
                ('movie_theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Showtime.movie_theater')),
                ('prices', models.ManyToManyField(to='Showtime.price')),
            ],
            options={
                'ordering': ['show_date', 'show_time'],
                'unique_together': {('film', 'show_date', 'show_time')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_code', models.CharField(default=Applications.Showtime.utils.generate_ticket_code, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('ticket_quantity', models.PositiveIntegerField(verbose_name='Cantidad de entradas')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Showtime.price')),
                ('show_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Showtime.show')),
            ],
        ),
    ]
