# Generated by Django 5.0.4 on 2024-10-30 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movie', '0002_remove_film_format_remove_film_language_film_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id_price', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Promoción')),
                ('amount', models.PositiveIntegerField(verbose_name='Precio')),
                ('ticket_quantity', models.PositiveIntegerField(verbose_name='Cantidad de entradas')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
            },
        ),
        migrations.CreateModel(
            name='Movie_Theater',
            fields=[
                ('id_movie_theater', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('capacity', models.PositiveIntegerField(null=True, verbose_name='Capacidad')),
                ('formats', models.ManyToManyField(to='Movie.format')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_code', models.AutoField(primary_key=True, serialize=False)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.film')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.format')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.language')),
                ('movie_theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Showtime.movie_theater')),
                ('prices', models.ManyToManyField(to='Showtime.price')),
            ],
            options={
                'ordering': ['show_date', 'show_time'],
                'unique_together': {('film', 'show_date', 'show_time')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=20, unique=True)),
                ('total_tickets', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Showtime.show')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Showtime.price')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_prices', to='Showtime.ticket')),
            ],
        ),
    ]
