# Generated by Django 5.0.4 on 2024-10-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Showtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='format',
        ),
        migrations.RemoveField(
            model_name='show',
            name='language',
        ),
    ]
