# Generated by Django 5.0.4 on 2024-11-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Showtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
