# Generated by Django 5.0.4 on 2024-10-20 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
        ('Showtime', '0002_remove_show_format_remove_show_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.format'),
        ),
        migrations.AddField(
            model_name='show',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.language'),
        ),
    ]
