# Generated by Django 5.0.4 on 2024-11-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Showtime', '0002_show_available_seats_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_price',
            old_name='quantity',
            new_name='selected_quantity',
        ),
    ]
