# Generated by Django 5.0.4 on 2024-12-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Showtime', '0003_rename_quantity_ticket_price_selected_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='description',
            field=models.CharField(default='Descripción', max_length=100, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='price',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promoIMG/', verbose_name='Imagen'),
        ),
    ]
